server:
  port: 8085
  servlet:
    context-path: /petclinic
spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/learn?currentSchema=petclinic
    username: petclinic
    password: petclinic
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/petclinic
          jwt-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: petclinic-api-client
      principle-attribute: preferred_username