spring:
  profiles:
    active: test

---
spring:
  config:
    activate:
      on-profile: test
  server:
    port: 8085

  datasource:
    url: ${PETCLINIC_DB_URL}
    username: ${PETCLINIC_DB_USERNAME}
    password: ${PETCLINIC_DB_PWD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

---

spring:
  config:
    activate:
      on-profile: test
  server:
    port: 8085

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    jpa:
      hibernate:
        ddl-auto: create-drop