spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  server:
    port: 8085

  datasource:
    url: ${PETCLINIC_DB_URL}
    username: ${PETCLINIC_DB_USERNAME}
    password: ${PETCLINIC_DB_PWD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

---
#
debug: true
spring:

#  config:
#    activate:
#      on-profile: test
#  server:
#    port: 8085
#
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    jpa:
      database-platform: org.hibernate.dialect.H2
      hibernate:
        ddl-auto: none
logging:
  level:
    org:
      hibernate: INFO
      springframework:
        data:
          jpa: INFO
        jdbc: DEBUG
