spring:
  profiles:
    active: dev

---

server:
  port: 8085

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${PETCLINIC_DB_URL}
    username: ${PETCLINIC_DB_USERNAME}
    password: ${PETCLINIC_DB_PWD}
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

---

server:
  port: 8085

#debug: true
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none



---